/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowRouteImport } from './routes/how'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrategiesRentToHmoRouteImport } from './routes/strategies_.rent-to-hmo'
import { Route as StrategiesSlugRouteImport } from './routes/strategies_.$slug'
import { Route as ApiPublicContactEnquiryRouteImport } from './routes/api/public/contact-enquiry'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRentToHmoRoute = StrategiesRentToHmoRouteImport.update({
  id: '/strategies_/rent-to-hmo',
  path: '/strategies/rent-to-hmo',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesSlugRoute = StrategiesSlugRouteImport.update({
  id: '/strategies_/$slug',
  path: '/strategies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactEnquiryRoute = ApiPublicContactEnquiryRouteImport.update({
  id: '/api/public/contact-enquiry',
  path: '/api/public/contact-enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/how': typeof HowRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/rent-to-hmo': typeof StrategiesRentToHmoRoute
  '/api/public/contact-enquiry': typeof ApiPublicContactEnquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/how': typeof HowRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/rent-to-hmo': typeof StrategiesRentToHmoRoute
  '/api/public/contact-enquiry': typeof ApiPublicContactEnquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/how': typeof HowRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies_/$slug': typeof StrategiesSlugRoute
  '/strategies_/rent-to-hmo': typeof StrategiesRentToHmoRoute
  '/api/public/contact-enquiry': typeof ApiPublicContactEnquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/home'
    | '/how'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies/$slug'
    | '/strategies/rent-to-hmo'
    | '/api/public/contact-enquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/home'
    | '/how'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies/$slug'
    | '/strategies/rent-to-hmo'
    | '/api/public/contact-enquiry'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/home'
    | '/how'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies_/$slug'
    | '/strategies_/rent-to-hmo'
    | '/api/public/contact-enquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  HowRoute: typeof HowRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StrategiesRoute: typeof StrategiesRoute
  TermsRoute: typeof TermsRoute
  StrategiesSlugRoute: typeof StrategiesSlugRoute
  StrategiesRentToHmoRoute: typeof StrategiesRentToHmoRoute
  ApiPublicContactEnquiryRoute: typeof ApiPublicContactEnquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies_/rent-to-hmo': {
      id: '/strategies_/rent-to-hmo'
      path: '/strategies/rent-to-hmo'
      fullPath: '/strategies/rent-to-hmo'
      preLoaderRoute: typeof StrategiesRentToHmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies_/$slug': {
      id: '/strategies_/$slug'
      path: '/strategies/$slug'
      fullPath: '/strategies/$slug'
      preLoaderRoute: typeof StrategiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-enquiry': {
      id: '/api/public/contact-enquiry'
      path: '/api/public/contact-enquiry'
      fullPath: '/api/public/contact-enquiry'
      preLoaderRoute: typeof ApiPublicContactEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  HowRoute: HowRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StrategiesRoute: StrategiesRoute,
  TermsRoute: TermsRoute,
  StrategiesSlugRoute: StrategiesSlugRoute,
  StrategiesRentToHmoRoute: StrategiesRentToHmoRoute,
  ApiPublicContactEnquiryRoute: ApiPublicContactEnquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
