/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrategiesRentToHmoRouteImport } from './routes/strategies_.rent-to-hmo'
import { Route as StrategiesSlugRouteImport } from './routes/strategies_.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRentToHmoRoute = StrategiesRentToHmoRouteImport.update({
  id: '/strategies_/rent-to-hmo',
  path: '/strategies/rent-to-hmo',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesSlugRoute = StrategiesSlugRouteImport.update({
  id: '/strategies_/$slug',
  path: '/strategies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/rent-to-hmo': typeof StrategiesRentToHmoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/rent-to-hmo': typeof StrategiesRentToHmoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terms': typeof TermsRoute
  '/strategies_/$slug': typeof StrategiesSlugRoute
  '/strategies_/rent-to-hmo': typeof StrategiesRentToHmoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies/$slug'
    | '/strategies/rent-to-hmo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies/$slug'
    | '/strategies/rent-to-hmo'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/strategies'
    | '/terms'
    | '/strategies_/$slug'
    | '/strategies_/rent-to-hmo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StrategiesRoute: typeof StrategiesRoute
  TermsRoute: typeof TermsRoute
  StrategiesSlugRoute: typeof StrategiesSlugRoute
  StrategiesRentToHmoRoute: typeof StrategiesRentToHmoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies_/rent-to-hmo': {
      id: '/strategies_/rent-to-hmo'
      path: '/strategies/rent-to-hmo'
      fullPath: '/strategies/rent-to-hmo'
      preLoaderRoute: typeof StrategiesRentToHmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies_/$slug': {
      id: '/strategies_/$slug'
      path: '/strategies/$slug'
      fullPath: '/strategies/$slug'
      preLoaderRoute: typeof StrategiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StrategiesRoute: StrategiesRoute,
  TermsRoute: TermsRoute,
  StrategiesSlugRoute: StrategiesSlugRoute,
  StrategiesRentToHmoRoute: StrategiesRentToHmoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
